// empty function test
fn test1() {
}

// let test
fn test2() {
    let x = 1;
}

// let with mut test
fn test3() {
    let mut x = 1;
}

// operator test
fn test4() {
    let mut x = 1;
    x = x + 1;
    x = x - 1;
    x = x * 1;
    x = x / 1;
    x = x % 1;
    x = x ** 1;
}

// operator error test
fn test5() {
    let x = 1;
    x = x + 1; // should error, cannot change immutable value
}

// function return test
fn test6() -> int {
    return 1;
}

// function arg and return test
fn test7(x: int) -> int {
    return x;
}

// function calling test
fn test8() {
    return test7(1);
}

// empty struct test
struct Test1 {
}

// struct test
struct Test2 {
    x: int,
}

// function with struct test
fn test9(x: Test2) -> Test1 {
    return Test1{};
}

// empty interface test
interface Test3 {
}

// interface test
interface Test4 {
    fn green(x: string) -> string;
}
